---
- name: Start influxdb
  ansible.builtin.service:
    name: influxdb
    state: started

- name: Restart influxdb
  ansible.builtin.service:
    name: influxdb
    state: restarted

- name: Create influxdb admin user
  community.general.influxdb_user:
    admin: true
    state: present
    user_name: "{{ influxdb_admin_user_name }}"
    user_password: "{{ influxdb_admin_user_password }}"
